sqlserver_local:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: ODBC Driver 17 for SQL Server
      server: LAPTOP-K8JGE4PG
      port: 1433
      database: health_verity_claims_dataset
      schema: dbo
      user: dbt_user
      password: Battlefield1@
      trust_cert: true
      encrypt: false

